
name: Release
on:
  push:
    branches:
      - main
  
jobs:
 test-and-release:
  name: Run tests and release
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v3.3.0
    - name: Setup Node.js
      uses: actions/setup-node@v3.6.0
      with:
        node-version: 18
    - name: Install dependencies
      run: npm i
    - name: Build
      run: npm run build:all
    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB }}
        NPM_TOKEN: ${{ secrets.NPM }}
      run: npm run semantic-release
